### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by mandogy** [jackun/USBqemu-wheel#10]
I just keep getting the files in a folder inside the zip files, not a DLL plugin.

**Comment by jackun** [comment]
Err, yes, and you open the zip and extract the dll from it.

**Comment by mandogy** [comment]
What I am saying is, after I extract the zip file, I just get a folder containing this
![image](https://user-images.githubusercontent.com/23311192/33829059-85b18fa8-de3c-11e7-8d02-55f96fb5618c.png)

**Comment by avih** [comment]
Which file do you download? When I go to the latest download - https://github.com/jackun/USBqemu-wheel/releases/tag/0.6.1-2 and then download and extract the file `USBqemu-wheel-0.6.1-2-2017-12-05-d2ad01a9-Release.zip`, then I see 3 files:
```
USBqemu-wheel-0.6.1.dll
USBqemu-wheel-0.6.1.lib
USBqemu-wheel-0.6.1.exp
```

And you probably need just the dll one if you just want to use it with PCSX2.

**Comment by jackun** [comment]
Ah yes, and don't confuse the `Clone or Download` button for a "real" download. Binaries are under `Releases` tab and for windows you want the ones named `USBqemu-wheel-blabla-Release.zip`

**Comment by mandogy** [comment]
When I view the release link, I see 11 files, none are what you listed 
![image](https://user-images.githubusercontent.com/23311192/33859417-d074345e-dea1-11e7-807f-a26b97b06fcd.png)

**Comment by radical-equanimity** [comment]
Dude, @mandogy , seriously? Click USBqemu-wheel-0.6.1-2-2017-12-05-d2ad01a9-Rlease.zip
