### ISSUE TITLE
Mouse/Keyboard as input

### ISSUE THREAD

**Issue by x8BitRain** [jackun/USBqemu-wheel#11]
There are a couple of PS2 games out there with full Mouse and Keyboard support like Half-Life, I recall being able to use the mouse and keyboard with the USBqemu Buzzer Mod plugin a while back, but it only worked on Windows from what I remember. Would be kinda neat!

**Comment by jackun** [comment]
It's fairly easy on windows, but I checked about how pad plugins are done on linux, well, on Xorg and it is going to be a pain. Xorg events get eaten by the "render" window so there's a hack to pass key events from GSdx etc to pad plugins, ugh.

**Comment by lowlyocean** [comment]
@jackun I second the request to enter text with keyboard

**Comment by jackun** [comment]
Got something running. Now the annoying part: how to capture and hide the cursor and ignore inputs when window is not active.

I've gone the easier route using raw input on windows and trying to shovel in evdev on linux. Dunno, might have to make the user select the keyboard device itself with evdev and also permission issues...

**Comment by lowlyocean** [comment]
Could you push and reference the commit in this Issue so I can help investigate?

**Comment by jackun** [comment]
Raw WIP commits at https://github.com/jackun/USBqemu-wheel/commits/develop  :P

**Comment by lowlyocean** [comment]
Can confirm, working in Socom II LAN lobby via XLink
 Fantastic!
