### ISSUE TITLE
Merge into PCSX2 master?

### ISSUE THREAD

**Issue by lowlyocean** [jackun/USBqemu-wheel#17]
Hello again, @jackun. Thanks again for helping integrate the Logitech PS2 headset- I know the SOCOM II community is grateful. I've managed to integrate enhancements (including Linux compatibility) to the networking plugin dev9ghzdrk into https://github.com/PCSX2/pcsx2/tree/master. I'm wondering if you have any plans to merge USBqemu-wheel into the main project? If you want any assistance on that front please let me know, would be glad to help

**Comment by jackun** [comment]
Hmm, I guess at some point. Easier for end-users for it to be preinstalled. But I'm in no hurry.

**Comment by seta-san** [comment]
It's an amazing plugin. It's time to be integrated may have come
