### ISSUE TITLE
Could not create IAudioClient

### ISSUE THREAD

**Issue by wllpwr4** [jackun/USBqemu-wheel#20]
Trying to play Lifeline over PSX2 and I began to get this message. I had a good long playthrough yesterday with no issues, and they started popping up today. I have tried many different combos of settings, like switching to Logitech USB Mic instead or using NOOP over WASAPI.
![psx](https://user-images.githubusercontent.com/40073754/64930178-415f3600-d7fc-11e9-892c-0da82b0854fb.PNG)
If further information is needed please let me know.

**Comment by jackun** [comment]
> AUDCLNT_E_DEVICE_INVALIDATED - This error code indicates that the endpoint device has been unplugged, or that the audio hardware or associated hardware resources have been reconfigured, disabled, removed, or otherwise made unavailable for use. 

I'll have to check if there's more to it but I'm guessing you did reconfigure the plugin to correct device? Are you using the onboard audio mic input or some USB headphones? If USB, maybe the cable is busted?

NOOP is a "no operation" device, just "records" silence.

**Comment by wllpwr4** [comment]
I'm sure it's configured to the correct device. It's using a USB connection, but I'm sure it works properly. It works fine through the Windows Control Panel. I don't think there's anything that is taking control of the device either.
