### ISSUE TITLE
Increase filter slider precision

### ISSUE THREAD

**Issue by choikiyeon** [jackun/USBqemu-wheel#21]
![K-003](https://user-images.githubusercontent.com/36502073/68208597-d7e9ef80-0014-11ea-9cb8-a452417550a4.jpg)

hello~~

The plugin is using so well

Is it possible to adjust 0.5 unit?

I have the desire to precisely set up  XD

**Comment by jackun** [comment]
Probably yes

**Comment by jackun** [comment]
Try it out: https://github.com/jackun/USBqemu-wheel/releases/tag/0.8.2-0
