### ISSUE TITLE
Singstar USB Mics 

### ISSUE THREAD

**Issue by D4rKT1mmy** [jackun/USBqemu-wheel#24]
It works but it lags and makes buzzing noises? 
How do i fix it?

**Comment by jackun** [comment]
If I'd know, it wouldn't. You can play with buffer sizes but it probably makes it lag too much. Also sound plugin settings may affect it.

**Comment by seta-san** [comment]
> If I'd know, it wouldn't. You can play with buffer sizes but it probably makes it lag too much. Also sound plugin settings may affect it.

Is it possible that the emulator/game is expecting it to come in at a usb1.1 bit rate and is instead getting usb2 or 3?

**Comment by jackun** [comment]
_Should_ work a little better in upcoming PCSX2 release.
