### ISSUE TITLE
No vertical mouse movement

### ISSUE THREAD

**Issue by niobium93** [jackun/USBqemu-wheel#25]
Mouse only moves horizontally.
Video: [https://youtu.be/Cw8os5_XfxA](https://youtu.be/Cw8os5_XfxA)
Using Arch Linux 5.6.2 kernel
PCSX2 1.5.0-20200327183028 - compiled on Apr  5 2020
libUSBqemu-wheel-0.8.2.so [Qemu USB Driver (Wheel) (Mar 26 2020) 0.8.2]
Both installed via AUR packages.
I also had to manually chmod these files to let the emulator access my mouse and keyboard:
/dev/input/by-path/pci-0000:02:00.0-usb-0:7.1:1.0-event-mouse
/dev/input/by-path/platform-i8042-serio-0-event-kbd
If you need more information, just ask.

**Comment by jackun** [comment]
> ev.u.rel.axis = INPUT_AXIS_X;

No wonder. Dunno how it worked for me then even :D

**Comment by niobium93** [comment]
I'm trying to build master, seems to build fine, but the resulting file fails to load
`[wx] /usr/lib32/pcsx2/libUSBqemu-wheel-0.8.2.so: undefined symbol: pa_stream_get_state`
Am I doing something wrong?

**Comment by niobium93** [comment]
It creates a 1.4 MiB file, whereas 8.2-3 is 421.4 KiB

**Comment by niobium93** [comment]
Figured it out: had to call cmake like this:
`cmake .. -DCMAKE_INSTALL_PREFIX=/usr/lib32/pcsx2 -DCMAKE_TOOLCHAIN_FILE=cmake/linux-compiler-i386-multilib.cmake -DPLUGIN_BUILD_DYNLINK_PULSE=FALSE`
You should update the instructions in your README.md

It works now though! Thanks for the speedy response <3

**Comment by jackun** [comment]
Must have been new of a pulseaudio header. They made some things `const`.
