### ISSUE TITLE
64bit version

### ISSUE THREAD

**Issue by shadow42085** [jackun/USBqemu-wheel#26]
I am trying to build it as a 64bit version and it fails any ideas?

**Comment by jackun** [comment]
Why? Is there a 64bit PCSX2?

**Comment by shadow42085** [comment]
yes there is that what I have been building out to for awhile now seams more stable for me

**Comment by jackun** [comment]
Where?

**Comment by shadow42085** [comment]
when you build the dev version is visual studio I have it set for 64bit release not 32bit

**Comment by jackun** [comment]
You can try, set `cmake -DPLUGIN_BUILD_64BIT=ON` to force it to not insert `-m32` everywhere.

**Comment by shadow42085** [comment]
I am building with visual studio or should I use mingw?

**Comment by shadow42085** [comment]
ok visual studio is spewing these errors
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2780	'_Ty std::min(std::initializer_list<_Elem>)': expects 1 arguments - 2 provided	C:\Users\hellf\Desktop\USBqemu-wheel-0.8.2-3\out\build\x64-Debug\USBqemu-wheel-0.8.2-3	C:\Users\hellf\Desktop\USBqemu-wheel-0.8.2-3\src\usb-mic\audiodev-wasapi.cpp	521	
Error	C2782	'const _Ty &std::min(const _Ty &,const _Ty &) noexcept(<expr>)': template parameter '_Ty' is ambiguous	C:\Users\hellf\Desktop\USBqemu-wheel-0.8.2-3\out\build\x64-Debug\USBqemu-wheel-0.8.2-3	C:\Users\hellf\Desktop\USBqemu-wheel-0.8.2-3\src\usb-mic\audiodev-wasapi.cpp	521	
Error	C2784	'const _Ty &std::min(const _Ty &,const _Ty &) noexcept(<expr>)': could not deduce template argument for 'const _Ty &' from 'size_t'	C:\Users\hellf\Desktop\USBqemu-wheel-0.8.2-3\out\build\x64-Debug\USBqemu-wheel-0.8.2-3	C:\Users\hellf\Desktop\USBqemu-wheel-0.8.2-3\src\usb-mic\audiodev-wasapi.cpp	521	
Error	C2784	'_Ty std::min(std::initializer_list<_Elem>,_Pr)': could not deduce template argument for 'std::initializer_list<_Elem>' from 'UINT32'	C:\Users\hellf\Desktop\USBqemu-wheel-0.8.2-3\out\build\x64-Debug\USBqemu-wheel-0.8.2-3	C:\Users\hellf\Desktop\USBqemu-wheel-0.8.2-3\src\usb-mic\audiodev-wasapi.cpp	521	
Error	C2780	'const _Ty &std::min(const _Ty &,const _Ty &,_Pr) noexcept(<expr>)': expects 3 arguments - 2 provided	C:\Users\hellf\Desktop\USBqemu-wheel-0.8.2-3\out\build\x64-Debug\USBqemu-wheel-0.8.2-3	C:\Users\hellf\Desktop\USBqemu-wheel-0.8.2-3\src\usb-mic\audiodev-wasapi.cpp	521

**Comment by jackun** [comment]
Did you pull latest master? It should have `std::min`fix there. But if there's more then just cast every :`:size()` etc call with size_t type to uint32_t, probably.

**Comment by shadow42085** [comment]
that must have did the trick by pulling directly from github must have bypass a problm with VS and loading folders direclty

**Comment by shadow42085** [comment]
and with that do you want me to send the warnings that VS gave?

**Comment by jackun** [comment]
No need. Most can be ignored for now hopefully.
