### ISSUE TITLE
emulator crashes when using eyetoy and pausing

### ISSUE THREAD

**Issue by seta-san** [jackun/USBqemu-wheel#50]
>start with eyetoy emulation.
>pause emulation
>resume emulation
>crash

**Comment by jackun** [comment]
Fixed some crashes with DShow and save state that on 64bit wanted to access freeze data pointer +4GB 😿 .
Some weirdness with DShow still like sometimes have to open settings multiple times with OBS virtual camera before it starts working.

**Comment by seta-san** [comment]
this problem does seem to be fixed.
