### ISSUE TITLE
DInput Filters no longer work

### ISSUE THREAD

**Issue by tocaedit** [jackun/USBqemu-wheel#54]
Hey jackun, Racer_S here. Had a quick play around in DInput with the newest build today. 

Noticed the steering/throttle/brake filters no longer save or work correctly in-game.

Also you can assign keyboard controls to Steering Axes, but they don't work in-game.  The other mappings work fine with keyboard.

Great work man love seeing it being updated after all these years, just some minor issues have cropped up since my first implementation and I'm sure you will get around to fixing it up.

**Comment by jackun** [comment]
Well, that's what you get if you stretch refactoring over a year+ 🤦 

Also, dunno if it was before like this or a new issue with float conversion but linear filter creates weird sudden jumps to left/right in the center 😕

**Comment by jackun** [comment]
Also PCSX2 team _might_ want to know if you're OK with plugin getting added to core PCSX2?

**Comment by tocaedit** [comment]
> Well, that's what you get if you stretch refactoring over a year+ 🤦

Understandable.

> Also, dunno if it was before like this or a new issue with float conversion but linear filter creates weird sudden jumps to left/right in the center 😕
> 
> E: seems it is GT4 itself with weird dead zone or something

Could be an off-by-one case, it used to work ok, the deadzone may not be zero'd correctly. It should behave just like it does on the graphic chart.

The negative deadzone was important to have in some games like Initial D where there is an in-game deadzone you cant remove.

> > Also you can assign keyboard controls to Steering Axes, but they don't work in-game.
> 
> Hmm, J/K worked for me.
> 
> Should be fixed in [0ec87bc](https://github.com/jackun/USBqemu-wheel/commit/0ec87bcba7cc0fb555c60e8fca89b86fe42034c5)

Sounds good!  And yeah I'm fine with them adding to PCSX2 Core. 

EC Sim Hardware no longer exists and the code was all written by me so you could remove that from the title if you'd like.
