### ISSUE TITLE
Linux Keyboard input support 

### ISSUE THREAD

**Issue by Zackmon** [jackun/USBqemu-wheel#58]
on Linux I am not able to get HID keyboard to work at all 

it gives me the following error whenever I try to choose my keyboard 

Cannot open /dev/input/by-path/pci-0000:44:00.3-usb-0:3:1.2-event-kbd
Cannot open /dev/input/by-path/pci-0000:44:00.3-usb-0:4:1.1-event-kbd
Cannot open /dev/input/by-path/pci-0000:44:00.3-usb-0:4:1.0-event-kbd
Cannot open /dev/input/by-path/pci-0000:44:00.3-usb-0:3:1.1-event-kbd

**Comment by jackun** [comment]
Could try adding your user to `input` group or whatever group /dev/input/* has.

**Comment by Zackmon** [comment]
Yes it's working great now 
Thank you for your support
