### ISSUE TITLE
HID keyboard not working

### ISSUE THREAD

**Issue by Vertabreak** [jackun/USBqemu-wheel#65]
installed latest .deb package 0.10.1, added udev rules, launched pcsx2 1.7, selected plugin, selected hid keyboard.
keyboard does not function in game, the games does seems to pickup that a keyboard is present but no buttons work. 

pcsx2 console read out:  
USB load config
Cannot open /dev/input/by-path/pci-0000:00:13.2-usb-0:1.1:1.1-event-kbd

searched around tried a bunch of things got no where any ideas?

**Comment by jackun** [comment]
> Could try adding your user to input group or whatever group /dev/input/* has.

https://github.com/jackun/USBqemu-wheel/issues/58

Probably not most secure workaround but have to do for now.

**Comment by Vertabreak** [comment]
already attempted this no dice.

**Comment by Vertabreak** [comment]
just discovered the problem the device was already in use by another program in this instance it was steam that was loaded at startup soon as it was closed it began to function.
