### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by slikk66** [jackun/USBqemu-wheel#68]
Hi, I'm using PCSX2 on windows 10.  I downloaded the latest x64 release, and have placed both the ZIP file and the unzipped contents into the PLUGINS directory.  However I don't see any option for QEMU under the USB plugin (where I think it should be) or the CONTROLLER plugin.

I'm using a PS3 rockband microphone which shows up as a LOGITECH microphone on windows, and it is connected and showing up in the windows USB section.

Am I doing something wrong?  I thought all I needed to do was place the files into the PLUGINS dir.

Thanks!

EDIT: I just reran the initial setup configuration and I see this in the logs:

[wx] Failed to load shared library 'C:\Program Files (x86)\PCSX2\Plugins\USBqemu-wheel-0.10.1-x64.dll' (error 193: unknown error c1)

**Comment by Florin9doi** [comment]
You most likely need the 32bit version

**Comment by slikk66** [comment]
Ok, ill give that a shot, im definitely on windows10 x64 though

**Comment by slikk66** [comment]
yep that did it.. I did confirm 64 bit OS.. but I see it now with the 32 bit plugin.  thanks!
